---
title: "Joining Vectors"
author: "Charles"
date: "2023-03-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(magrittr)
```

## Vectors
- unidimensional matrices
- has data types

## What are dataframes
two dimensional matrix

```{r}
surveys <- read.csv(file = "../data-raw/surveys.csv")
str(surveys)
```

#   Create vectors wiht the 'c()' function
c("stuff")

```{r}
c("luna", "Avi", "Anita", "James", "Charles", "Damian", "Davinder") -> our_names
str(our_names)
```
# seq() can make sequences of different step lengths
```{r}
my_numbers <- seq(-100, 100, 10)
letters
LETTERS
```

# Creating data frames with vectors
use data.frame()
```{r}
data.frame(names = our_names, numbers = my_numbers[1:7])
```

```{r}
data.frame(names = our_names, numbers = 1)
```
```{r}
data.frame(names = rep(our_names, 2), numbers = c(2, 5.5))
```
```{r}
length <- c(2.2, 2.1, 2.7, 3.0, 3.1, 2.5, 1.9, 1.1, 3.5, 2.9)
width <- c(1.3, 2.2, 1.5, 4.5, 3.1, NA, 1.8, 0.5, 2.0, 2.7)
height <- c(9.6, 7.6, 2.2, 1.5, 4.0, 3.0, 4.5, 2.3, 7.5, 3.2)
data.frame(genus = rep("Taxus", 10), species = rep("baccata", 10), length = length, width = width, height = height)
```

```{r}
length <- c(2.2, 2.1, 2.7, 3.0, 3.1, 2.5, 1.9, 1.1, 3.5, 2.9)
width <- c(1.3, 2.2, 1.5, 4.5, 3.1, NA, 1.8, 0.5, 2.0, 2.7)
height <- c(9.6, 7.6, 2.2, 1.5, 4.0, 3.0, 4.5, 2.3, 7.5, 3.2)
data.frame(genus = rep("Taxus", 10), species = rep("baccata", 10), length = length, width = width, height = height) -> df

"min"
min(df$length, na.rm = TRUE)
min(df$width, na.rm = TRUE)
min(df$height, na.rm = TRUE)

"max"
max(df$length, na.rm = TRUE)
max(df$width, na.rm = TRUE)
max(df$height, na.rm = TRUE)

"sum"
sum(df$length, na.rm = TRUE)
sum(df$width, na.rm = TRUE)
sum(df$height, na.rm = TRUE)

"avg"
mean(df$length, na.rm = TRUE)
mean(df$width, na.rm = TRUE)
mean(df$height, na.rm = TRUE)

"vol"
length * width * height
vol <- length * width * height

""

```

```{r}
d <- surveys$year
```

```{r}
surveys[1:10, 1:2]
```

```{r}
surveys[, "hindfoot_length"] -> hindfoot_length
```

```{r}
surveys[["record_id"]] %>% 
  head()
```

```{r}
surveys_weight <- surveys$weight
surveys_month <- surveys["month"]
mean(surveys$hindfoot_length, na.rm = TRUE)
```

















